name: Build

on:
  push:
    paths:
    - **
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Setup qemu-action
      uses: docker/setup-qemu-action@v1
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1

    - name: CNB Login
      uses: docker/login-action@v1.6.0
      with:
        registry: docker.cnb.cool
        username: cnb
        password: ${{ secrets.CNB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          docker.cnb.cool/rtvsmirror/vanjoge/docker-ubuntu-lxde-novnc:latest

